export interface City {
  en: string;
  uk: string;
  ru: string;
}

export const ukraineCities: City[] = [
  { en: "Kyiv", uk: "Київ", ru: "Киев" },
  { en: "Vinnytsia", uk: "Вінниця", ru: "Винница" },
  { en: "Lutsk", uk: "Луцьк", ru: "Луцк" },
  { en: "Dnipro", uk: "Дніпро", ru: "Днепр" },
  { en: "Zhytomyr", uk: "Житомир", ru: "Житомир" },
  { en: "Uzhhorod", uk: "Ужгород", ru: "Ужгород" },
  { en: "Zaporizhzhia", uk: "Запоріжжя", ru: "Запорожье" },
  { en: "Ivano-Frankivsk", uk: "Івано-Франківськ", ru: "Ивано-Франковск" },
  { en: "Kropyvnytskyi", uk: "Кропивницький", ru: "Кропивницкий" },
  { en: "Lviv", uk: "Львів", ru: "Львов" },
  { en: "Mykolaiv", uk: "Миколаїв", ru: "Николаев" },
  { en: "Odesa", uk: "Одеса", ru: "Одесса" },
  { en: "Poltava", uk: "Полтава", ru: "Полтава" },
  { en: "Rivne", uk: "Рівне", ru: "Ровно" },
  { en: "Sumy", uk: "Суми", ru: "Сумы" },
  { en: "Ternopil", uk: "Тернопіль", ru: "Тернополь" },
  { en: "Kharkiv", uk: "Харків", ru: "Харьков" },
  { en: "Kherson", uk: "Херсон", ru: "Херсон" },
  { en: "Khmelnytskyi", uk: "Хмельницький", ru: "Хмельницкий" },
  { en: "Cherkasy", uk: "Черкаси", ru: "Черкассы" },
  { en: "Chernivtsi", uk: "Чернівці", ru: "Черновцы" },
  { en: "Chernihiv", uk: "Чернігів", ru: "Чернигов" },
  { en: "Simferopol", uk: "Сімферополь", ru: "Симферополь" },
  { en: "Donetsk", uk: "Донецьк", ru: "Донецк" },
  { en: "Luhansk", uk: "Луганськ", ru: "Луганск" },
  { en: "Mariupol", uk: "Маріуполь", ru: "Мариуполь" },
  { en: "Kryvyi Rih", uk: "Кривий Ріг", ru: "Кривой Рог" },
  { en: "Bila Tserkva", uk: "Біла Церква", ru: "Белая Церковь" },
  { en: "Kremenchuk", uk: "Кременчук", ru: "Кременчуг" },
  { en: "Melitopol", uk: "Мелітополь", ru: "Мелитополь" },
  { en: "Berdiansk", uk: "Бердянськ", ru: "Бердянск" },
  { en: "Nikopol", uk: "Нікополь", ru: "Никополь" },
  { en: "Sloviansk", uk: "Слов'янськ", ru: "Славянск" },
  { en: "Uman", uk: "Умань", ru: "Умань" },
  { en: "Konotop", uk: "Конотоп", ru: "Конотоп" },
  { en: "Shostka", uk: "Шостка", ru: "Шостка" },
  { en: "Berdychiv", uk: "Бердичів", ru: "Бердичев" },
  { en: "Mukachevo", uk: "Мукачево", ru: "Мукачево" },
  { en: "Drohobych", uk: "Дрогобич", ru: "Дрогобыч" },
  { en: "Nizhyn", uk: "Ніжин", ru: "Нежин" },
  { en: "Novomoskovsk", uk: "Новомосковськ", ru: "Новомосковск" },
  { en: "Kovel", uk: "Ковель", ru: "Ковель" },
  { en: "Kalush", uk: "Калуш", ru: "Калуш" },
  { en: "Korosten", uk: "Коростень", ru: "Коростень" },
  { en: "Oleksandriia", uk: "Олександрія", ru: "Александрия" },
].sort((a, b) => (a.en === "Kyiv" ? -1 : b.en === "Kyiv" ? 1 : a.uk.localeCompare(b.uk, "uk")));
