export interface City {
  en: string;
  uk: string;
  ru: string;
}

export const ukraineCities: City[] = [
  { en: "Kyiv", uk: "Київ", ru: "Киев" },
  { en: "Vinnytsia", uk: "Вінниця", ru: "Винница" },
  { en: "Lutsk", uk: "Луцьк", ru: "Луцк" },
  { en: "Dnipro", uk: "Дніпро", ru: "Днепр" },
  { en: "Zhytomyr", uk: "Житомир", ru: "Житомир" },
  { en: "Uzhhorod", uk: "Ужгород", ru: "Ужгород" },
  { en: "Zaporizhzhia", uk: "Запоріжжя", ru: "Запорожье" },
  { en: "Ivano-Frankivsk", uk: "Івано-Франківськ", ru: "Ивано-Франковск" },
  { en: "Kropyvnytskyi", uk: "Кропивницький", ru: "Кропивницкий" },
  { en: "Lviv", uk: "Львів", ru: "Львов" },
  { en: "Mykolaiv", uk: "Миколаїв", ru: "Николаев" },
  { en: "Odesa", uk: "Одеса", ru: "Одесса" },
  { en: "Poltava", uk: "Полтава", ru: "Полтава" },
  { en: "Rivne", uk: "Рівне", ru: "Ровно" },
  { en: "Sumy", uk: "Суми", ru: "Сумы" },
  { en: "Ternopil", uk: "Тернопіль", ru: "Тернополь" },
  { en: "Kharkiv", uk: "Харків", ru: "Харьков" },
  { en: "Kherson", uk: "Херсон", ru: "Херсон" },
  { en: "Khmelnytskyi", uk: "Хмельницький", ru: "Хмельницкий" },
  { en: "Cherkasy", uk: "Черкаси", ru: "Черкассы" },
  { en: "Chernivtsi", uk: "Чернівці", ru: "Черновцы" },
  { en: "Chernihiv", uk: "Чернігів", ru: "Чернигов" },
  { en: "Simferopol", uk: "Сімферополь", ru: "Симферополь" },
  { en: "Donetsk", uk: "Донецьк", ru: "Донецк" },
  { en: "Luhansk", uk: "Луганськ", ru: "Луганск" },
  { en: "Mariupol", uk: "Маріуполь", ru: "Мариуполь" },
  { en: "Kryvyi Rih", uk: "Кривий Ріг", ru: "Кривой Рог" },
  { en: "Bila Tserkva", uk: "Біла Церква", ru: "Белая Церковь" },
  { en: "Kremenchuk", uk: "Кременчук", ru: "Кременчуг" },
  { en: "Melitopol", uk: "Мелітополь", ru: "Мелитополь" },
  { en: "Berdiansk", uk: "Бердянськ", ru: "Бердянск" },
  { en: "Nikopol", uk: "Нікополь", ru: "Никополь" },
  { en: "Sloviansk", uk: "Слов'янськ", ru: "Славянск" },
  { en: "Uman", uk: "Умань", ru: "Умань" },
  { en: "Konotop", uk: "Конотоп", ru: "Конотоп" },
  { en: "Shostka", uk: "Шостка", ru: "Шостка" },
  { en: "Berdychiv", uk: "Бердичів", ru: "Бердичев" },
  { en: "Mukachevo", uk: "Мукачево", ru: "Мукачево" },
  { en: "Drohobych", uk: "Дрогобич", ru: "Дрогобыч" },
  { en: "Nizhyn", uk: "Ніжин", ru: "Нежин" },
  { en: "Novomoskovsk", uk: "Новомосковськ", ru: "Новомосковск" },
  { en: "Kovel", uk: "Ковель", ru: "Ковель" },
  { en: "Kalush", uk: "Калуш", ru: "Калуш" },
  { en: "Korosten", uk: "Коростень", ru: "Коростень" },
  { en: "Oleksandriia", uk: "Олександрія", ru: "Александрия" },
  { en: "Kamianets-Podilskyi", uk: "Кам'янець-Подільський", ru: "Каменец-Подольский" },
  { en: "Boryspil", uk: "Бориспіль", ru: "Борисполь" },
  { en: "Brovary", uk: "Бровари", ru: "Бровары" },
  { en: "Irpin", uk: "Ірпінь", ru: "Ирпень" },
  { en: "Bucha", uk: "Буча", ru: "Буча" },
  { en: "Fastiv", uk: "Фастів", ru: "Фастов" },
  { en: "Vasylkiv", uk: "Васильків", ru: "Васильков" },
  { en: "Vyshneve", uk: "Вишневе", ru: "Вишневое" },
  { en: "Obukhiv", uk: "Обухів", ru: "Обухов" },
  { en: "Boyarka", uk: "Боярка", ru: "Боярка" },
  { en: "Vyshhorod", uk: "Вишгород", ru: "Вышгород" },
  { en: "Pereyaslav", uk: "Переяслав", ru: "Переяслав" },
  { en: "Slavutych", uk: "Славутич", ru: "Славутич" },
  { en: "Kolomyia", uk: "Коломия", ru: "Коломыя" },
  { en: "Stryi", uk: "Стрий", ru: "Стрый" },
  { en: "Chervonohrad", uk: "Червоноград", ru: "Червоноград" },
  { en: "Sambir", uk: "Самбір", ru: "Самбор" },
  { en: "Boryslav", uk: "Борислав", ru: "Борислав" },
  { en: "Truskavets", uk: "Трускавець", ru: "Трускавец" },
  { en: "Nadvirna", uk: "Надвірна", ru: "Надворная" },
  { en: "Dolyna", uk: "Долина", ru: "Долина" },
  { en: "Novovolynsk", uk: "Нововолинськ", ru: "Нововолынск" },
  { en: "Volodymyr", uk: "Володимир", ru: "Владимир" },
  { en: "Sarny", uk: "Сарни", ru: "Сарны" },
  { en: "Dubno", uk: "Дубно", ru: "Дубно" },
  { en: "Varash", uk: "Вараш", ru: "Вараш" },
  { en: "Netishyn", uk: "Нетішин", ru: "Нетишин" },
  { en: "Zviahel", uk: "Звягель", ru: "Звягель" },
  { en: "Malyn", uk: "Малин", ru: "Малин" },
  { en: "Zhmerynka", uk: "Жмеринка", ru: "Жмеринка" },
  { en: "Mohyliv-Podilskyi", uk: "Могилів-Подільський", ru: "Могилев-Подольский" },
  { en: "Koziatyn", uk: "Козятин", ru: "Казатин" },
  { en: "Khmilnyk", uk: "Хмільник", ru: "Хмельник" },
  { en: "Smila", uk: "Сміла", ru: "Смела" },
  { en: "Zolotonosha", uk: "Золотоноша", ru: "Золотоноша" },
  { en: "Kaniv", uk: "Канів", ru: "Канев" },
  { en: "Lubny", uk: "Лубни", ru: "Лубны" },
  { en: "Myrhorod", uk: "Миргород", ru: "Миргород" },
  { en: "Horishni Plavni", uk: "Горішні Плавні", ru: "Горишние Плавни" },
  { en: "Okhtyrka", uk: "Охтирка", ru: "Ахтырка" },
  { en: "Romny", uk: "Ромни", ru: "Ромны" },
  { en: "Hlukhiv", uk: "Глухів", ru: "Глухов" },
  { en: "Pryluky", uk: "Прилуки", ru: "Прилуки" },
  { en: "Izmail", uk: "Ізмаїл", ru: "Измаил" },
  { en: "Chornomorsk", uk: "Чорноморськ", ru: "Черноморск" },
  { en: "Bilhorod-Dnistrovskyi", uk: "Білгород-Дністровський", ru: "Белгород-Днестровский" },
  { en: "Podilsk", uk: "Подільськ", ru: "Подольск" },
  { en: "Voznesensk", uk: "Вознесенськ", ru: "Вознесенск" },
  { en: "Yuzhnoukrainsk", uk: "Южноукраїнськ", ru: "Южноукраинск" },
  { en: "Pervomaisk", uk: "Первомайськ", ru: "Первомайск" },
  { en: "Kakhovka", uk: "Каховка", ru: "Каховка" },
  { en: "Skadovsk", uk: "Скадовськ", ru: "Скадовск" },
  { en: "Enerhodar", uk: "Енергодар", ru: "Энергодар" },
  { en: "Tokmak", uk: "Токмак", ru: "Токмак" },
].sort((a, b) => (a.en === "Kyiv" ? -1 : b.en === "Kyiv" ? 1 : a.uk.localeCompare(b.uk, "uk")));
